### ISSUE TITLE
Show password

### ISSUE THREAD

**Issue by barun511** [barun511/thor#6]
The show password checkbox is not working

**Comment by agdhruv** [comment]
It's working for me. You must be connected to the internet to be able to access the feature as I have used a jQuery CDN.

**Comment by barun511** [comment]
I'm tempted to just store a local copy of jquery. What do you think?

**Comment by agdhruv** [comment]
Nop, the application can never be viewed without being connected to the internet anyway. Optimisation. Does it work for you now, btw?

**Comment by barun511** [comment]
Of course it can, it's on a local network!

Shouldn't we be optimizing for time over space?

On Nov 16, 2016 9:54 PM, "Dhruv Agarwal" notifications@github.com wrote:

Nop, the application can never be viewed without being connected to the
internet anyway. Optimisation. Does it work for you now, btw?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/barun511/thor/issues/6#issuecomment-260992853, or mute
the thread

**Comment by barun511** [comment]
Anyway, I'll check it out :) also I'll be updating the API to allow C++
tomorrow

**Comment by agdhruv** [comment]
Cool. Using CDN is better for both space and time optimisation. Read online. But yes, I forgot its on a local network. Then I'll store a local copy right before deploying it finally.

**Comment by agdhruv** [comment]
We can close this issue. Close if its fine with you now.

**Comment by barun511** [comment]
Read, you're right.
